### ISSUE TITLE
"queue.js" error if the queue is empty

### ISSUE THREAD

**Issue by quentinmay** [AlfRagnar/discord-bot#5]
Trying the "queue" command while the queue is empty creates an error. Its because line 14 of queue.js tries to use musicQueue.songs even though musicQueue.songs is undefined. Can be fixed by first checking if musicQueue.songs exists.

**Comment by AlfRagnar** [comment]
Will have a look at this. Seems the issue stems from constants being defined before checking if the constants they are based on have any value or not so they try to fetch information from undefined.
